### ISSUE TITLE
[frontend::repo] User Authentication

### ISSUE THREAD

**Issue by nazjur** [foodpanda-capstone-6/fe#7]
Creation of the frontend authentication pages, requesting to merge:

1.  Include the folder for components
2. Add `Register.tsx` file for user registration
3. Add `Login.tsx` file for user login and authentication
4. Modify `App.tsx` to include the `Register` component

**Comment by noellimx** [comment]
Reopening issue. Please close issue after associated [PR #8 ](https://github.com/foodpanda-capstone-6/fe/pull/8) has been merged :)
